/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupSuccessRouteImport } from './routes/signup-success'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WitnessesIndexRouteImport } from './routes/witnesses/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as SharedAccessIndexRouteImport } from './routes/shared-access/index'
import { Route as PromisesIndexRouteImport } from './routes/promises/index'
import { Route as ItemsIndexRouteImport } from './routes/items/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as TransactionsNewRouteImport } from './routes/transactions/new'
import { Route as TransactionsMyContactTransactionsRouteImport } from './routes/transactions/my-contact-transactions'
import { Route as TransactionsIdRouteImport } from './routes/transactions/$id'
import { Route as ItemsNewRouteImport } from './routes/items/new'
import { Route as ContactsContactIdRouteImport } from './routes/contacts/$contactId'
import { Route as WitnessesInviteTokenRouteImport } from './routes/witnesses/invite.$token'
import { Route as SharedAccessViewGrantIdRouteImport } from './routes/shared-access/view.$grantId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupSuccessRoute = SignupSuccessRouteImport.update({
  id: '/signup-success',
  path: '/signup-success',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WitnessesIndexRoute = WitnessesIndexRouteImport.update({
  id: '/witnesses/',
  path: '/witnesses/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedAccessIndexRoute = SharedAccessIndexRouteImport.update({
  id: '/shared-access/',
  path: '/shared-access/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromisesIndexRoute = PromisesIndexRouteImport.update({
  id: '/promises/',
  path: '/promises/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/transactions/new',
  path: '/transactions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsMyContactTransactionsRoute =
  TransactionsMyContactTransactionsRouteImport.update({
    id: '/transactions/my-contact-transactions',
    path: '/transactions/my-contact-transactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsNewRoute = ItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const WitnessesInviteTokenRoute = WitnessesInviteTokenRouteImport.update({
  id: '/witnesses/invite/$token',
  path: '/witnesses/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedAccessViewGrantIdRoute = SharedAccessViewGrantIdRouteImport.update({
  id: '/shared-access/view/$grantId',
  path: '/shared-access/view/$grantId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/signup-success': typeof SignupSuccessRoute
  '/verify-email': typeof VerifyEmailRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/items/new': typeof ItemsNewRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions/my-contact-transactions': typeof TransactionsMyContactTransactionsRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/contacts/': typeof ContactsIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/promises/': typeof PromisesIndexRoute
  '/shared-access/': typeof SharedAccessIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/witnesses/': typeof WitnessesIndexRoute
  '/shared-access/view/$grantId': typeof SharedAccessViewGrantIdRoute
  '/witnesses/invite/$token': typeof WitnessesInviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/signup-success': typeof SignupSuccessRoute
  '/verify-email': typeof VerifyEmailRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/items/new': typeof ItemsNewRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions/my-contact-transactions': typeof TransactionsMyContactTransactionsRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/contacts': typeof ContactsIndexRoute
  '/items': typeof ItemsIndexRoute
  '/promises': typeof PromisesIndexRoute
  '/shared-access': typeof SharedAccessIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/witnesses': typeof WitnessesIndexRoute
  '/shared-access/view/$grantId': typeof SharedAccessViewGrantIdRoute
  '/witnesses/invite/$token': typeof WitnessesInviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/signup-success': typeof SignupSuccessRoute
  '/verify-email': typeof VerifyEmailRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/items/new': typeof ItemsNewRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions/my-contact-transactions': typeof TransactionsMyContactTransactionsRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/contacts/': typeof ContactsIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/promises/': typeof PromisesIndexRoute
  '/shared-access/': typeof SharedAccessIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/witnesses/': typeof WitnessesIndexRoute
  '/shared-access/view/$grantId': typeof SharedAccessViewGrantIdRoute
  '/witnesses/invite/$token': typeof WitnessesInviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/signup-success'
    | '/verify-email'
    | '/contacts/$contactId'
    | '/items/new'
    | '/transactions/$id'
    | '/transactions/my-contact-transactions'
    | '/transactions/new'
    | '/contacts/'
    | '/items/'
    | '/promises/'
    | '/shared-access/'
    | '/transactions/'
    | '/witnesses/'
    | '/shared-access/view/$grantId'
    | '/witnesses/invite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/signup-success'
    | '/verify-email'
    | '/contacts/$contactId'
    | '/items/new'
    | '/transactions/$id'
    | '/transactions/my-contact-transactions'
    | '/transactions/new'
    | '/contacts'
    | '/items'
    | '/promises'
    | '/shared-access'
    | '/transactions'
    | '/witnesses'
    | '/shared-access/view/$grantId'
    | '/witnesses/invite/$token'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/signup-success'
    | '/verify-email'
    | '/contacts/$contactId'
    | '/items/new'
    | '/transactions/$id'
    | '/transactions/my-contact-transactions'
    | '/transactions/new'
    | '/contacts/'
    | '/items/'
    | '/promises/'
    | '/shared-access/'
    | '/transactions/'
    | '/witnesses/'
    | '/shared-access/view/$grantId'
    | '/witnesses/invite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SignupSuccessRoute: typeof SignupSuccessRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  ItemsNewRoute: typeof ItemsNewRoute
  TransactionsIdRoute: typeof TransactionsIdRoute
  TransactionsMyContactTransactionsRoute: typeof TransactionsMyContactTransactionsRoute
  TransactionsNewRoute: typeof TransactionsNewRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
  PromisesIndexRoute: typeof PromisesIndexRoute
  SharedAccessIndexRoute: typeof SharedAccessIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  WitnessesIndexRoute: typeof WitnessesIndexRoute
  SharedAccessViewGrantIdRoute: typeof SharedAccessViewGrantIdRoute
  WitnessesInviteTokenRoute: typeof WitnessesInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-success': {
      id: '/signup-success'
      path: '/signup-success'
      fullPath: '/signup-success'
      preLoaderRoute: typeof SignupSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/witnesses/': {
      id: '/witnesses/'
      path: '/witnesses'
      fullPath: '/witnesses/'
      preLoaderRoute: typeof WitnessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-access/': {
      id: '/shared-access/'
      path: '/shared-access'
      fullPath: '/shared-access/'
      preLoaderRoute: typeof SharedAccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promises/': {
      id: '/promises/'
      path: '/promises'
      fullPath: '/promises/'
      preLoaderRoute: typeof PromisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/new': {
      id: '/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/my-contact-transactions': {
      id: '/transactions/my-contact-transactions'
      path: '/transactions/my-contact-transactions'
      fullPath: '/transactions/my-contact-transactions'
      preLoaderRoute: typeof TransactionsMyContactTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/new': {
      id: '/items/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof ItemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/witnesses/invite/$token': {
      id: '/witnesses/invite/$token'
      path: '/witnesses/invite/$token'
      fullPath: '/witnesses/invite/$token'
      preLoaderRoute: typeof WitnessesInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-access/view/$grantId': {
      id: '/shared-access/view/$grantId'
      path: '/shared-access/view/$grantId'
      fullPath: '/shared-access/view/$grantId'
      preLoaderRoute: typeof SharedAccessViewGrantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SignupSuccessRoute: SignupSuccessRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ContactsContactIdRoute: ContactsContactIdRoute,
  ItemsNewRoute: ItemsNewRoute,
  TransactionsIdRoute: TransactionsIdRoute,
  TransactionsMyContactTransactionsRoute:
    TransactionsMyContactTransactionsRoute,
  TransactionsNewRoute: TransactionsNewRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
  PromisesIndexRoute: PromisesIndexRoute,
  SharedAccessIndexRoute: SharedAccessIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  WitnessesIndexRoute: WitnessesIndexRoute,
  SharedAccessViewGrantIdRoute: SharedAccessViewGrantIdRoute,
  WitnessesInviteTokenRoute: WitnessesInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
